# Originally Source From https://nodered.org/docs/getting-started/docker#docker-stack--docker-compose
# Augmented to make it more to my liking and used with some of my ansible roles.

version: '3.4'

services:
  ide:
    build:
      context: ./
      # args:
      #   DOCKER_GRP: ${DOCKER_GRP}
    image: ide:0.0.1
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - type: volume
        source: node-red-data
        target: /data
      # - type: bind
      #   source: ./data
      #   target: /data

      # NOTE To remove in production as a potential security risk as it can see the current
      # local directory and dockerfile and docker-compose.yml
      - type: bind
        source: ./
        target: /local
      # Allow the NodeRED IDE access to the Docker instance
      # NOTE To remove in production as a security risk usefult for
      # a dev IDE but need to be watched
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # To allow easier backup of the information into a safe directory
      - type: bind
        source: ./backup
        target: /backup
      # Allows injection of an SSH key for the projects and conections
      - type: bind
        source: ./ssh
        target: /usr/src/node-red/.ssh
      # Allows injection of an certs key for the conections
      - type: bind
        source: ./certs
        target: /certs
    # # Required for permission for the docker socket
    # group_add:
    #   - ${DOCKER_GRP}
    #   # - docker
    environment:
      TZ: Europe/London
    healthcheck:
      test: curl -s http://localhost:1880 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  node-red-data:

networks:
  node-red-net: